# Generated by Django 5.1.7 on 2025-04-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_active_remove_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='urgent_tasks',
            new_name='uncompleted_tasks',
        ),
    ]
